{
 "title": "Grafana Dashboard for Veeam Enterprise Manager",
 "description": "Grafana Dashboard for Veeam Enterprise Manager RESTful API - Pulls out all the VBR Information, Jobs, Jobs Duration, Protected VMs, Replicated VMs, etc.",
 "tags": [
  "Veeam",
  "Enterprise Manager"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Enterprise Manager - Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": {
      "content": "![Veeam Backup Enterprise Manager - Dashboard](https://www.jorgedelacruz.es/wp-content/uploads/2020/01/enterprise-manager-1.png)\n\n\n\n"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_em_overview",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupServers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
       ]
      }
     ]
    },
    {
     "title": "Warning VMs results",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B == 2\n", "type": "math" },
      { "expression": "$C == 2\n", "type": "math" }
     ]
    },
    {
     "title": "Failed VMs results",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B == 0\n", "type": "math" },
      { "expression": "$C == 0\n", "type": "math" }
     ]
    },
    {
     "title": "Success VMs results",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B == 1\n", "type": "math" },
      { "expression": "$C == 1\n", "type": "math" }
     ]
    },
    {
     "title": "Backup Repository Lists",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Total repository space .*/" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Inactive VMs results",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B == 3\n", "type": "math" },
      { "expression": "$C == 3\n", "type": "math" }
     ]
    },
    {
     "title": "Disabled VMs results",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B == 4\n", "type": "math" },
      { "expression": "$C == 4\n", "type": "math" }
     ]
    },
    {
     "title": "En Course VMs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B == 5", "type": "math" },
      { "expression": "$C == 5", "type": "math" }
     ]
    },
    {
     "title": "En Course VMs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B == 5", "type": "math" },
      { "expression": "$C == 5", "type": "math" }
     ]
    },
    {
     "title": "Backup Repository - Usage Capacity",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "100.0*(1-($A/$B))", "type": "math" },
      { "expression": "100.0*(1-($D/$E))", "type": "math" }
     ]
    },
    {
     "title": "Status Veeam A-D",
     "type": "stat",
     "gridPos": { "h": 13, "w": 9, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Status Veeam [A-D].*/" },
       "itemTag": { "filter": "" },
       "measurement": "veeam_em_overview",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamRepositoryServers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Status Veeam E-Z a-z",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Status Veeam [E-Za-z].*/" },
       "itemTag": { "filter": "" },
       "measurement": "veeam_em_overview",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamRepositoryServers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Status SQL",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Status SQL .*/" },
       "itemTag": { "filter": "" },
       "measurement": "veeam_em_overview",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamRepositoryServers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Veeam Backup Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "veeamserver",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $col",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "CPU utilization" },
       "itemTag": { "filter": "" },
       "measurement": "win_cpu",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "Percent_Privileged_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Privileged Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% User Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Interrupt Time" ], "type": "alias" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $col",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "Memory utilization" },
       "itemTag": { "filter": "" },
       "measurement": "win_mem",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Available Bytes" ], "type": "alias" }
        ],
        [
         { "params": [ "Pool_Nonpaged_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pool non-paged Bytes" ], "type": "alias" }
        ],
        [
         { "params": [ "Pool_Paged_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pool paged Bytes" ], "type": "alias" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "Uptime" },
       "itemTag": { "filter": "" },
       "measurement": "win_system",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT \"System_Up_Time\" FROM \"win_system\" WHERE (\"host\" =~ /^$vboserver$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "System_Up_Time" ], "type": "field" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "C:: Total space",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "C:: Total space" },
       "itemTag": { "filter": "" },
       "measurement": "win_disk",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$veeamserver$/ ) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $col",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": {
        "filter": "Interface vmxnet3 Ethernet Adapter(Ethernet0): Bits received"
       },
       "itemTag": {
        "filter": "Application: Interface vmxnet3 Ethernet Adapter(Ethernet0)"
       },
       "measurement": "win_net",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes received" ], "type": "alias" }
        ],
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes sent" ], "type": "alias" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "vmxnet3 Ethernet Adapter" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "$tag_host $col",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": {
        "filter": "Interface vmxnet3 Ethernet Adapter(Ethernet0): Bits sent"
       },
       "itemTag": {
        "filter": "Application: Interface vmxnet3 Ethernet Adapter(Ethernet0)"
       },
       "measurement": "win_net",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes received" ], "type": "alias" }
        ],
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes sent" ], "type": "alias" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "vmxnet3 Ethernet Adapter" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "D:: Total space",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "D:: Total space" },
       "itemTag": { "filter": "" },
       "measurement": "win_disk",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$veeamserver$/ ) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "veeamserver",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Last Result",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "repeat": "backupjob",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Backup Job .*/" },
       "itemTag": { "filter": "" },
       "measurement": "veeam_em_job_sessions",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Time",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_instance",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Backup Job .*/" },
       "itemTag": { "filter": "" },
       "measurement": "win_disk",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$veeamserver$/ ) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Veeam Backup Jobs Per VM Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_instance",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Backup Job .*/" },
       "itemTag": { "filter": "" },
       "measurement": "win_disk",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$veeamserver$/ ) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Replicated VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "veeamserver",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Last Result",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Replication Job .*/" },
       "itemTag": { "filter": "" },
       "measurement": "veeam_em_job_sessions",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Time",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_instance",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Replication Job .*/" },
       "itemTag": { "filter": "" },
       "measurement": "win_disk",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$veeamserver$/ ) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Veeam Backup Jobs Per VM Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_instance",
       "application": { "filter": "" },
       "group": { "filter": "Discovered hosts" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "host": { "filter": "Test-Veeam" },
       "item": { "filter": "/Replication Job .*/" },
       "itemTag": { "filter": "" },
       "measurement": "win_disk",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$veeamserver$/ ) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}